name = "DaemonWorker"
uuid = "73b1f5ce-f66a-45c6-8f4e-ee74572d910a"
authors = ["TEC <git@tecosaur.net>"]
version = "0.1.0"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
